# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Homepage
version: "1.2.0"
slug: homepage
description: Homepage addon for HA
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armv7
  - armv6
  - amd64
  - arm64
init: false
image: "ghcr.io/gethomepage/homepage:latest"

